import ai from './outlined/ai.svg'
import ps from './outlined/ps.svg'
import blender from './outlined/blender.svg'
import figma from './outlined/figma.svg'
import html from './outlined/html.svg'
import css from './outlined/css.svg'
import javascript from './outlined/javascript.svg'
import typescript from './outlined/typescript.svg'
import node from './outlined/node.svg'
import react from './outlined/react.svg'
import next from './outlined/next.svg'
import aws from './outlined/aws.svg'
import sqlserver from './outlined/sql-server.svg'
import git from './outlined/git.svg'
import github from './outlined/github.svg'
import autocad from './outlined/autocad.svg'
import sketchup from './outlined/sketchup.svg'
import lumion from './outlined/lumion.svg'

export { ai, ps, blender, figma, html, css, javascript, typescript, next, react, node, aws, sqlserver, git, github, autocad, sketchup, lumion }
